#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Run from the repo root regardless of where this was invoked from.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# .env.local is the only env file this repo gitignores, and the repo is PUBLIC.
# Everything this wizard records goes there and nowhere else.
ENV_FILE=".env.local"

banner "Tulsa Training — Cross Country: first production deploy"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools and the tree before anything reaches production."

if ! git check-ignore -q "$ENV_FILE"; then
  warn "$ENV_FILE is NOT gitignored, and this repo is public."
  warn "Fix .gitignore before continuing — the production key would be committed."
  exit 1
fi
printf '  %s✓%s %s is gitignored\n' "$GREEN" "$RESET" "$ENV_FILE"

for tool in npx vercel curl node; do
  command -v "$tool" >/dev/null 2>&1 || { warn "missing required tool: $tool"; exit 1; }
done
printf '  %s✓%s npx, vercel, curl, node present\n' "$GREEN" "$RESET"

VERCEL_USER=$(vercel whoami 2>/dev/null || true)
[[ -n "$VERCEL_USER" ]] || { warn "vercel is not logged in — run: vercel login"; exit 1; }
printf '  %s✓%s vercel logged in as %s\n' "$GREEN" "$RESET" "$VERCEL_USER"

say ""
say "Building locally first, so a broken build fails here and not on Vercel."
npm run build >/dev/null 2>&1 || { warn "npm run build failed — fix it before deploying"; exit 1; }
printf '  %s✓%s production build succeeds\n' "$GREEN" "$RESET"

note "on branch: $(git rev-parse --abbrev-ref HEAD)"
say ""
confirm "Deploy this branch to production?" || { say "Nothing changed. Re-run when ready."; exit 0; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Convex: create the production deployment"
say "This pushes the schema and functions to a NEW production deployment,"
say "separate from the dev one (fine-eagle-220). Dev data is not touched."
say ""
confirm "Run 'npx convex deploy'?" || { say "Stopped before touching production."; exit 0; }

DEPLOY_LOG=$(mktemp)
npx convex deploy -y 2>&1 | tee "$DEPLOY_LOG" || { warn "convex deploy failed — see output above"; exit 1; }

PROD_CONVEX_URL=$(grep -oE 'https://[a-z0-9-]+\.convex\.cloud' "$DEPLOY_LOG" | head -n1 || true)
rm -f "$DEPLOY_LOG"

if [[ -z "$PROD_CONVEX_URL" ]]; then
  say ""
  warn "Couldn't read the production URL out of the deploy output."
  open_url "https://dashboard.convex.dev/t/james-7ecd5/tt-world-tour"
  step "Pick the PRODUCTION deployment (not fine-eagle-220)."
  step "Copy its URL — it looks like https://something-animal-123.convex.cloud"
  ask PROD_CONVEX_URL "Paste the production Convex URL:"
fi

[[ "$PROD_CONVEX_URL" == https://*.convex.cloud ]] || { warn "that doesn't look like a Convex URL: $PROD_CONVEX_URL"; exit 1; }
printf '  %s✓%s production Convex: %s\n' "$GREEN" "$RESET" "$PROD_CONVEX_URL"
write_env PROD_CONVEX_URL "$PROD_CONVEX_URL"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Convex: set the production trainer key"
say "Destructive mutations (resetChallenge, simulateDay, deleteEntry) check"
say "this key server-side. It is never bundled and never committed — a trainer"
say "types it once per device."
say ""
say "Production needs its OWN key. The dev one must not be reused."

# An earlier run may already have made one. Rotating it would lock out every
# trainer device holding the old key, so keep it unless explicitly asked.
EXISTING_KEY=$(_existing PROD_ADMIN_KEY || true)
NEW_KEY=""
if [[ -n "$EXISTING_KEY" ]]; then
  say ""
  note "a production key from an earlier run is recorded in $ENV_FILE"
  warn "generating a new one logs out every trainer device using the old one"
  if confirm "Keep the existing production key?"; then
    NEW_KEY="$EXISTING_KEY"
    printf '  %s✓%s keeping the existing key\n' "$GREEN" "$RESET"
  fi
fi

if [[ -z "$NEW_KEY" ]]; then
  # Crockford-ish alphabet: no 0/O/1/I, so nobody mistypes it off a card.
  # Generated with node rather than `tr </dev/urandom | head`, which trips
  # pipefail on SIGPIPE. 256 % 32 == 0, so there is no modulo bias.
  NEW_KEY=$(node -e "const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',b=require('crypto').randomBytes(16);let s='';for(let i=0;i<16;i++)s+=a[b[i]%a.length];console.log(s.match(/.{4}/g).join('-'))")
  [[ ${#NEW_KEY} -eq 19 ]] || { warn "key generation failed"; exit 1; }

  say ""
  printf '  %s%s  %s  %s\n' "$BOLD" "$GREEN" "$NEW_KEY" "$RESET"
  say ""
  warn "Write this down NOW. Convex will not show it back to you, and trainers"
  warn "need it to unlock the entry form on the gym computer."
  pause "Saved it somewhere safe? Press Enter."
fi

npx convex env set ADMIN_KEY "$NEW_KEY" --prod >/dev/null 2>&1 \
  || { warn "couldn't set ADMIN_KEY on production"; exit 1; }
printf '  %s✓%s ADMIN_KEY set on the production deployment\n' "$GREEN" "$RESET"
write_env PROD_ADMIN_KEY "$NEW_KEY"
note "recorded in $ENV_FILE (gitignored) as PROD_ADMIN_KEY — nothing reads it, it is just a copy"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Vercel: link the project and point it at production Convex"
say "VITE_CONVEX_URL is baked into the built bundle, so it must be the"
say "PRODUCTION Convex URL, not the dev one."

vercel link --yes >/dev/null 2>&1 || { warn "vercel link failed"; exit 1; }
printf '  %s✓%s project linked\n' "$GREEN" "$RESET"

# Replace rather than add, so re-running this wizard is safe.
vercel env rm VITE_CONVEX_URL production --yes >/dev/null 2>&1 || true
printf '%s' "$PROD_CONVEX_URL" | vercel env add VITE_CONVEX_URL production >/dev/null 2>&1 \
  || { warn "couldn't set VITE_CONVEX_URL on Vercel"; exit 1; }
printf '  %s✓%s VITE_CONVEX_URL → %s\n' "$GREEN" "$RESET" "$PROD_CONVEX_URL"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Vercel: deploy the site"
say "Vercel builds from source with the env var above. This creates a public URL."
say ""
confirm "Deploy to production now?" || { say "Backend is live; the site is not. Re-run to finish."; exit 0; }

SITE_LOG=$(mktemp)
vercel deploy --prod --yes 2>&1 | tee "$SITE_LOG" || { warn "vercel deploy failed — see output above"; exit 1; }
SITE_URL=$(grep -oE 'https://[a-zA-Z0-9.-]+\.vercel\.app' "$SITE_LOG" | tail -n1 || true)
rm -f "$SITE_LOG"

if [[ -z "$SITE_URL" ]]; then
  ask SITE_URL "Paste the production site URL Vercel printed:"
fi
write_env PROD_SITE_URL "$SITE_URL"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify production is actually locked down"
say "The whole point of the key is that a stranger cannot wipe the challenge."
say "Proving it on production, not just dev."

_mutation() {
  curl -s -X POST "$PROD_CONVEX_URL/api/mutation" \
    -H 'Content-Type: application/json' -d "$1"
}

FAILED=0

say ""
step "resetChallenge with NO key must be rejected"
if _mutation '{"path":"worldTour:resetChallenge","args":{},"format":"json"}' | grep -q '"status":"error"'; then
  printf '  %s✓%s rejected\n' "$GREEN" "$RESET"
else
  printf '  %s✗ ACCEPTED — production is NOT protected%s\n' "$RED" "$RESET"; FAILED=1
fi

step "resetChallenge with a WRONG key must be rejected"
if _mutation '{"path":"worldTour:resetChallenge","args":{"key":"not-the-key"},"format":"json"}' | grep -q 'Not authorized'; then
  printf '  %s✓%s rejected\n' "$GREEN" "$RESET"
else
  printf '  %s✗ ACCEPTED — production is NOT protected%s\n' "$RED" "$RESET"; FAILED=1
fi

step "the real key must be accepted"
if _mutation "{\"path\":\"worldTour:verifyAdmin\",\"args\":{\"key\":\"$NEW_KEY\"},\"format\":\"json\"}" | grep -q '"status":"success"'; then
  printf '  %s✓%s accepted\n' "$GREEN" "$RESET"
else
  printf '  %s✗ REJECTED — trainers will not be able to log in%s\n' "$RED" "$RESET"; FAILED=1
fi

step "members must still be able to log meters without a key"
if _mutation '{"path":"worldTour:logEntry","args":{"machine":"Row","amount":100},"format":"json"}' | grep -q '"status":"success"'; then
  printf '  %s✓%s open, as designed\n' "$GREEN" "$RESET"
  _mutation "{\"path\":\"worldTour:resetChallenge\",\"args\":{\"key\":\"$NEW_KEY\"},\"format\":\"json\"}" >/dev/null
  note "test entry cleaned up; production is back to zero"
else
  printf '  %s✗ blocked — nobody can log anything%s\n' "$RED" "$RESET"; FAILED=1
fi

if (( FAILED )); then
  say ""
  warn "Production is NOT in a safe state. Do not hand the URL out yet."
  SKIPPED+=("re-check the ADMIN_KEY on production: npx convex env get ADMIN_KEY --prod")
else
  say ""
  printf '  %s✓ production is locked down correctly%s\n' "$GREEN" "$RESET"
fi

say ""
[[ -n "$SITE_URL" ]] && open_url "$SITE_URL"
step "Open the site, click 'Trainer login', and paste the key above."
step "Then hit 'TV mode' on the gym TV browser window."
SKIPPED+=("21 postcards still to shoot, including tulsa.jpg (the gym + crew photo)")
SKIPPED+=("set CHALLENGE_WINDOW in src/config.ts when the dates are decided")
pause "Done?"

finish
