#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "${BASH_SOURCE[0]}")/.."
ENV_FILE=".env.local"
TOTAL_STAGES=6

banner "Cross Country — launch day at the gym"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Is production actually ready?"
say "Checking the live deployment before anyone is standing in front of it."

ask PROD_SITE_URL "Site URL:"
ask PROD_CONVEX_URL "Convex production URL:"
ask PROD_ADMIN_KEY "Trainer key:"
[[ -n "$PROD_SITE_URL" && -n "$PROD_CONVEX_URL" && -n "$PROD_ADMIN_KEY" ]] || {
  warn "need all three to continue"; exit 1; }
write_env PROD_SITE_URL "$PROD_SITE_URL"

say ""
_mut() { curl -s -X POST "$PROD_CONVEX_URL/api/mutation" -H 'Content-Type: application/json' -d "$1"; }
FAILED=0

step "site is up"
if [[ "$(curl -s -o /dev/null -w '%{http_code}' "$PROD_SITE_URL")" == "200" ]]; then
  printf '  %s✓%s\n' "$GREEN" "$RESET"
else printf '  %s✗ site is not responding%s\n' "$RED" "$RESET"; FAILED=1; fi

step "a stranger cannot wipe the challenge"
if _mut '{"path":"worldTour:resetChallenge","args":{"key":"guess"},"format":"json"}' | grep -q '"status":"error"'; then
  printf '  %s✓%s\n' "$GREEN" "$RESET"
else printf '  %s✗ RESET IS OPEN — stop and fix this%s\n' "$RED" "$RESET"; FAILED=1; fi

step "a stranger cannot log meters"
if _mut '{"path":"worldTour:logEntry","args":{"machine":"Row","amount":100},"format":"json"}' | grep -q '"status":"error"'; then
  printf '  %s✓%s\n' "$GREEN" "$RESET"
else printf '  %s✗ logging is open to anyone%s\n' "$RED" "$RESET"; FAILED=1; fi

step "your trainer key works"
if _mut "{\"path\":\"worldTour:verifyAdmin\",\"args\":{\"key\":\"$PROD_ADMIN_KEY\"},\"format\":\"json\"}" | grep -q '"status":"success"'; then
  printf '  %s✓%s\n' "$GREEN" "$RESET"
else printf '  %s✗ that key is not accepted%s\n' "$RED" "$RESET"; FAILED=1; fi

say ""
(( FAILED )) && { warn "Do not go live until these pass."; exit 1; }
printf '  %sProduction is ready.%s\n' "$GREEN" "$RESET"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Print the QR cards"
say "This is the entire rollout for member self-logging. Without the cards,"
say "nobody but a trainer can log anything."
say ""
step "Unlock this browser first: Trainer login, then paste the key."
note "$PROD_ADMIN_KEY"
open_url "$PROD_SITE_URL"
pause "Unlocked? Press Enter."
say ""
open_url "$PROD_SITE_URL/qr"
step "Hit Print. Five cards, one per machine."
step "Tape one to each machine, at eye level from where you stand on it."
warn "The cards contain the log token. Do not post them online."
pause "Cards printed and up? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Set up the gym TV"
say "This screen is going to sit here for a month unattended."
say ""
step "Open the site in the TV's browser and press TV mode."
step "Turn OFF the screensaver and any sleep timer on that machine."
step "Turn off auto-updates or anything that can pop a dialog over it."
note "Double-click the map, or the small 'exit' label, to leave TV mode."
say ""
warn "Do NOT unlock trainer mode on the TV browser. If it is unlocked, the"
warn "entry form and the Reset button sit on the gym TV all month."
pause "TV is up in TV mode and locked? Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Brief the trainers"
say "Four things. The second one is the one that actually matters."
say ""
step "1. Members log their own meters — point them at the QR on the machine."
say ""
step "2. THE ASSAULT BIKE READS IN MILES. Everything else reads in meters."
note "   The app knows, and switches the label to Miles when you pick it."
note "   Type exactly the number on the screen. Never convert in your head."
note "   Typing a mile count into a meters box loses about 8 km per entry."
say ""
step "3. Trainer login is for logging on behalf of someone, and for undo."
note "   Recent entries has an x next to each one. Use it for mistakes."
say ""
step "4. 'Reset to zero' wipes the entire challenge. It is behind the trainer"
note "   key for a reason. Nobody touches it during the month."
say ""
say "The key, if a trainer needs it on their own device:"
note "$PROD_ADMIN_KEY"
pause "Team briefed? Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "One real test, end to end"
say "Log a genuine entry from a phone, exactly as a member would."
say ""
step "Scan the QR on the rower with your phone camera."
step "Type a real number off the machine and hit Log it."
step "You should see: 'You just moved us N meters down the road.'"
step "Small numbers cross Everest at 8,848 m and fire a celebration on the TV."
say ""
pause "Done it? Press Enter to check what landed."

TOTAL=$(curl -s -X POST "$PROD_CONVEX_URL/api/query" -H 'Content-Type: application/json' \
  -d '{"path":"worldTour:getSummary","args":{},"format":"json"}' \
  | node -e "let d='';process.stdin.on('data',c=>d+=c).on('end',()=>{try{console.log(JSON.parse(d).value.totalJourney)}catch{console.log('?')}})")
say ""
printf '  the challenge currently reads %s%s%s meters\n' "$BOLD" "$TOTAL" "$RESET"
say ""
if [[ "$TOTAL" == "0" ]]; then
  warn "Nothing landed. The scan or the log did not go through — sort that"
  warn "out now, while you are standing next to it."
  pause
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Start from zero"
say "Clear the test entries so the gym starts on a clean slate."
say ""
if confirm "Wipe everything and start the challenge at zero?"; then
  _mut "{\"path\":\"worldTour:resetChallenge\",\"args\":{\"key\":\"$PROD_ADMIN_KEY\"},\"format\":\"json\"}" >/dev/null
  printf '  %s✓%s back to zero\n' "$GREEN" "$RESET"
else
  note "left as-is — whatever is logged now counts"
fi

say ""
say "That is it. 8,473,348 meters to Tulsa."
SKIPPED+=("set CHALLENGE_WINDOW in src/config.ts if you want a countdown and pace")
SKIPPED+=("21 postcards still to shoot — bash scripts/postcards.sh")
pause

finish
