#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "${BASH_SOURCE[0]}")/.."

CONFIG="src/config.ts"
DIR="public/postcards"

# Every landmark still missing a photo.
#   milestone name (must match config.ts exactly) | filename | kind | search terms
#
# kind: find  = a photo of a real place, searched for
#       make  = a number card, designed to match the existing ones
#       shoot = James's own camera, no substitute
WANTED=(
  "The 100th Meridian|meridian.jpg|find|great plains prairie horizon"
  "Into Mountain time|mountain-time.jpg|find|route 66 highway sign desert"
  "Albuquerque|albuquerque.jpg|find|Albuquerque hot air balloons"
  "The Painted Desert|painted-desert.jpg|find|Painted Desert Arizona"
  "Flagstaff|flagstaff.jpg|find|Flagstaff Arizona mountains"
  "The Colorado River at Needles|needles.jpg|find|Colorado River Arizona desert"
  "Barstow|barstow.jpg|find|Route 66 Mojave desert road"
  "Red rock country|red-rock.jpg|find|southern Utah red rock canyon"
  "Salt Lake City|salt-lake-city.jpg|find|Salt Lake City Utah"
  "The Continental Divide|divide.jpg|find|Continental Divide Rocky Mountains"
  "Denver|denver.jpg|find|Denver skyline mountains"
  "Omaha|omaha.jpg|find|Omaha Nebraska skyline"
  "Des Moines|des-moines.jpg|find|Des Moines Iowa"
  "The shore of Lake Erie|lake-erie.jpg|find|Lake Erie shoreline"
  "6 million meters|6-million.jpg|make|"
  "Philadelphia — the Rocky Steps|philadelphia.jpg|find|Philadelphia Museum of Art steps"
  "Pittsburgh|pittsburgh.jpg|find|Pittsburgh bridges skyline"
  "Columbus|columbus.jpg|find|Columbus Ohio skyline"
  "Indianapolis|indianapolis.jpg|find|Indianapolis skyline"
  "8 million meters|8-million.jpg|make|"
  "100 KM TO GO|100-to-go.jpg|make|"
  "TULSA. HOME.|tulsa.jpg|shoot|"
)

# ── Which ones are actually still outstanding? ────────────────────────────
# A postcard counts as done only when the file is on disk AND config.ts points
# at it. Either half alone is a broken celebration, so both are checked.
PENDING=()
DONE_COUNT=0
for row in "${WANTED[@]}"; do
  IFS='|' read -r _name file _kind _q <<< "$row"
  if [[ -f "$DIR/$file" ]] && grep -qF "img: '/postcards/$file'" "$CONFIG"; then
    DONE_COUNT=$((DONE_COUNT + 1))
  else
    PENDING+=("$row")
  fi
done

TOTAL_STAGES=$(( ${#PENDING[@]} + 1 ))

# wire_postcard NAME FILE adds the img: line to that milestone in config.ts.
# Done in node rather than sed because the names contain em-dashes and periods.
wire_postcard() {
  node - "$1" "$2" <<'NODE'
const fs = require('fs')
const [, , name, file] = process.argv
const p = 'src/config.ts'
let s = fs.readFileSync(p, 'utf8')
const needle = "name: '" + name + "',"
if (s.includes("img: '/postcards/" + file + "'")) { console.log('already'); process.exit(0) }
if (!s.includes(needle)) { console.error('no milestone named ' + name); process.exit(2) }
fs.writeFileSync(p, s.replace(needle, needle + " img: '/postcards/" + file + "',"))
console.log('wired')
NODE
}

# looks_like_jpeg FILE: real photo, or a 3 KB error page someone right-clicked?
looks_like_jpeg() {
  local f="$1" magic size
  [[ -f "$f" ]] || return 1
  size=$(wc -c < "$f" | tr -d ' ')
  (( size > 20000 )) || return 1
  magic=$(od -An -tx1 -N3 "$f" | tr -d ' \n')
  [[ "$magic" == "ffd8ff" ]]
}

banner "Cross Country — the missing postcards"

if (( ${#PENDING[@]} == 0 )); then
  say ""
  printf '  %s✓ All %s postcards are already in place.%s\n\n' "$GREEN" "$DONE_COUNT" "$RESET"
  exit 0
fi

_clear
printf '\n  %s%s of %s postcards already done. %s to go.%s\n\n' "$BOLD" "$DONE_COUNT" "${#WANTED[@]}" "${#PENDING[@]}" "$RESET"
say "For each one: save a photo into $DIR with the exact filename shown,"
say "and this will check it and wire it into the config for you."
say ""
note "Landscape, and the wider the better — they are used as a full-bleed"
note "backdrop on the gym TV, so anything portrait gets badly cropped."
note ""
note "Stop any time with Ctrl-C. Re-running picks up where you left off."
pause "Press Enter to start."

for row in "${PENDING[@]}"; do
  IFS='|' read -r NAME FILE KIND QUERY <<< "$row"
  stage "$NAME"

  case "$KIND" in
    find)
      say "A photo of this place, for the celebration backdrop."
      say ""
      step "Pick something wide, and moody enough to read white text over."
      note "It is a backdrop, not a card: the milestone name and meter count"
      note "are drawn on top of it. Avoid anything with big text of its own."

      note "Unsplash is free to use commercially — these end up on Instagram"
      note "share cards, so avoid anything you would have to license."
      open_url "https://unsplash.com/s/photos/${QUERY// /-}"
      ;;
    make)
      say "A backdrop with no place to photograph — a mood, not a landmark."
      say ""
      step "Run: node scripts/backdrops.mjs, and open the URL it prints."
      step "It draws these and writes them for you."
      note "DO NOT print the number into the image. Celebration already draws"
      note "the milestone name and its meter count on top, over a wash that"
      note "takes the photo down to 28%. A number in the image is a second"
      note "number arguing with the real one — halfway.jpg used to read"
      note "\"20 MILLION\" behind a foreground saying 4,236,674."
      ;;
    shoot)
      say "This is the finish frame. It has to be your own photo."
      say ""
      step "The gym and the crew — this is what fills the screen at 8,473,348 m,"
      step "the moment the whole month lands. No stock photo can do it."
      warn "Every other postcard is a place. This one is the people."
      ;;
  esac

  say ""
  printf '  %sSave it as:%s  %s%s/%s%s\n' "$BOLD" "$RESET" "$GREEN" "$DIR" "$FILE" "$RESET"
  say ""

  while true; do
    pause "Saved it? Press Enter to check."
    if looks_like_jpeg "$DIR/$FILE"; then
      printf '  %s✓%s %s looks like a real JPEG\n' "$GREEN" "$RESET" "$FILE"
      break
    fi
    if [[ ! -f "$DIR/$FILE" ]]; then
      warn "$DIR/$FILE isn't there yet — check the filename exactly."
    else
      warn "$DIR/$FILE is there but doesn't look like a usable JPEG"
      note "(under 20 KB, or not actually a JPEG — a saved error page does this)"
    fi
    if confirm "Skip this one for now and come back later?"; then
      SKIPPED+=("$NAME → $DIR/$FILE")
      continue 2
    fi
  done

  if wire_postcard "$NAME" "$FILE" >/dev/null; then
    printf '  %s✓%s wired into %s\n' "$GREEN" "$RESET" "$CONFIG"
  else
    warn "couldn't wire $NAME into $CONFIG — add the img: line by hand"
    SKIPPED+=("add img: '/postcards/$FILE' to the '$NAME' milestone in $CONFIG")
  fi
done

# ── Final ─────────────────────────────────────────────────────────────────
stage "Check it all still builds"

WIRED=$(grep -cF "img: '/postcards/" "$CONFIG" || true)
say "config.ts now points at $WIRED postcards out of 41 milestones."
say ""

MISSING=$(node - <<'NODE'
const fs = require('fs')
const s = fs.readFileSync('src/config.ts', 'utf8')
const have = new Set(fs.readdirSync('public/postcards'))
const refs = [...s.matchAll(/img: '\/postcards\/([^']+)'/g)].map((m) => m[1])
const missing = refs.filter((r) => !have.has(r))
console.log(missing.join(' '))
NODE
)
if [[ -n "$MISSING" ]]; then
  warn "config points at files that aren't on disk: $MISSING"
  SKIPPED+=("missing files referenced by config.ts: $MISSING")
else
  printf '  %s✓%s every postcard config references exists on disk\n' "$GREEN" "$RESET"
fi

if npx tsc --noEmit >/dev/null 2>&1; then
  printf '  %s✓%s typecheck clean\n' "$GREEN" "$RESET"
else
  warn "typecheck failed — config.ts may have been mangled; check git diff"
fi

if npm run build >/dev/null 2>&1; then
  printf '  %s✓%s production build succeeds\n' "$GREEN" "$RESET"
else
  warn "build failed — check git diff on $CONFIG"
fi

say ""
step "Review with: git diff src/config.ts"
step "Then commit the photos and the config together."
if (( WIRED < 41 )); then
  SKIPPED+=("$(( 41 - WIRED )) milestone(s) still have no postcard — re-run this wizard")
fi
pause "Done?"

finish
