// GENERATED by scripts/state-crossings.mjs — do not edit by hand.
// Re-run it whenever the route in config.ts changes:
//
//   node scripts/state-crossings.mjs
//
// Which states the road passes through, and the meter mark at which each is
// first entered. The map fills a state in once the gym reaches it, tinted by
// the act that got them there — so this is what turns the country from a
// backdrop into a record of the journey.
export type StateCrossing = { id: string; name: string; m: number }

export const STATE_CROSSINGS: StateCrossing[] = [
  { id: '40', name: 'Oklahoma', m: 0 },
  { id: '48', name: 'Texas', m: 384_000 },
  { id: '35', name: 'New Mexico', m: 660_000 },
  { id: '04', name: 'Arizona', m: 1_244_000 },
  { id: '32', name: 'Nevada', m: 1_904_000 },
  { id: '06', name: 'California', m: 1_908_000 },
  { id: '49', name: 'Utah', m: 2_832_000 },
  { id: '08', name: 'Colorado', m: 3_468_000 },
  { id: '31', name: 'Nebraska', m: 4_072_000 },
  { id: '19', name: 'Iowa', m: 4_604_000 },
  { id: '17', name: 'Illinois', m: 5_072_000 },
  { id: '26', name: 'Michigan', m: 5_372_000 },
  { id: '18', name: 'Indiana', m: 5_452_000 },
  { id: '39', name: 'Ohio', m: 5_536_000 },
  { id: '42', name: 'Pennsylvania', m: 5_888_000 },
  { id: '34', name: 'New Jersey', m: 6_348_000 },
  { id: '36', name: 'New York', m: 6_440_000 },
  { id: '54', name: 'West Virginia', m: 7_028_000 },
  { id: '29', name: 'Missouri', m: 7_884_000 },
  { id: '20', name: 'Kansas', m: 8_320_000 },
]
